
#pragma block ASM
#include "z.S"
/**
 * 🫎 Mooseworth is here!
 * Author: Brendan,Lucas
 * Contributors: Brendan,Lucas
 */

.section .data
		
main_$2011055596$l2wgD85bQP4N6l0kZ7A6JtZSFwk0avcQGPVpMT9XdJCVrsx39C1YyyWCXxvHIFZx:
	.asciz "Brendan Lucas"
		
.section .text
#pragma section main
		
TYPE main_$Person$eIHgwsve4vKqSFKAaGxyIYIhm7mmK8e6aF3ZLsEXROVz1UOlv63RAq21rR4GEmlL
		
	TYPE_FIELD 
			BYTE, 
undefined, 
			
TYPE_END
		
/* Variable myName */

/* Accessor */
		
MOV RDI, REF(main_$2011055596$l2wgD85bQP4N6l0kZ7A6JtZSFwk0avcQGPVpMT9XdJCVrsx39C1YyyWCXxvHIFZx)
				
		
VAR main_$myName$4JErxcDbCLuOXZDOvH82t2ILEdojFmAquBX3LiyKK2G80SlpBZj0jtSsTnmoqcfM, RDI, RDI
SCOPE SET main_$myName$4JErxcDbCLuOXZDOvH82t2ILEdojFmAquBX3LiyKK2G80SlpBZj0jtSsTnmoqcfM, RDI
		
#pragma block end
