on:
  issues:
    types: [labeled]
jobs:
  enforce-owner-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check if unauthorized user applied protected label
        uses: actions/github-script@v7
        with:
          script: |
            const protectedLabels = ['Version', 'Won\t Fix', 'Invalid', 'Duplicate'];
            const labelName = context.payload.label.name;
            const sender = context.payload.sender.login;

            if (protectedLabels.includes(labelName)) {
              const { data: collaborators } = await github.rest.repos.listCollaborators({
                owner: context.repo.owner,
                repo: context.repo.repo,
                affiliation: 'direct'
              });

              const isOwner = collaborators.some(user => 
                user.login === sender && (user.permissions.admin || user.permissions.maintain)
              );

              if (!isOwner) {
                // Remove the label
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: labelName
                });
                console.log(`Removed protected label "${labelName}" added by unauthorized user ${sender}`);
              }
            }
